### ISSUE TITLE
[linux]后端程序未启动

### ISSUE THREAD

**Issue by kukat** [lh232510/ChiaMiner#1]
版本： linux-1.3.4.1
按照教程配置好，启动 `./cmd start` 时出现错误信息

![image](https://user-images.githubusercontent.com/107503/117333016-12af3b00-aecb-11eb-8e83-7bc4aabaa501.png)

日志如下

![image](https://user-images.githubusercontent.com/107503/117333107-2f4b7300-aecb-11eb-9e8c-f035db8af564.png)

**Comment by Abezetibul** [comment]
嗨，您是否設法在Linux上運行？

**Comment by kukat** [comment]
> 嗨，您是否設法在Linux上運行？

是的，ubuntu server 20.04.2

**Comment by Cornil79** [comment]
I have the same problem. Ubuntu server 20.04

**Comment by chuwt** [comment]
请下载最新的 linux-0.3.2版本
