### ISSUE TITLE
答案最后上报时间 --- and no payments

### ISSUE THREAD

**Issue by DanDod** [lh232510/ChiaMiner#7]
Worker has been working for 3 days, but I have not received payments
![image](https://user-images.githubusercontent.com/83855475/117527817-64dd8280-afd7-11eb-828e-1422848c5942.png)
![image](https://user-images.githubusercontent.com/83855475/117527827-79217f80-afd7-11eb-9e14-4ad15235c0ee.png)
![image](https://user-images.githubusercontent.com/83855475/117527835-8474ab00-afd7-11eb-8a00-ff0143c44126.png)

**Comment by jevelir** [comment]
у многих так же,uupool молчит.решения нет.

**Comment by Alxgth** [comment]
> Worker has been working for 3 days, but I have not received payments
> ![image](https://user-images.githubusercontent.com/83855475/117527817-64dd8280-afd7-11eb-828e-1422848c5942.png)
> ![image](https://user-images.githubusercontent.com/83855475/117527827-79217f80-afd7-11eb-9e14-4ad15235c0ee.png)
> ![image](https://user-images.githubusercontent.com/83855475/117527835-8474ab00-afd7-11eb-8a00-ff0143c44126.png)

Got the same error. When just started it was ok about a few hours, but then "---" and no more payments.

**Comment by Alxgth** [comment]
This error since 06 may 2021

**Comment by snoopek13** [comment]
I have similar problem

**Comment by chuwt** [comment]
The more plots file you have, the more chance you will upload your calculation.
Before you upload your calculation , there is a filter in chia harvester.
We will improve this later for lower NetSpace.

**Comment by Alxgth** [comment]
> The more plots file you have, the more chance you will upload your calculation.
> Before you upload your calculation , there is a filter in chia harvester.
> We will improve this later for lower NetSpace.

Now i have about 10tb of plots and nothing paid in last days. My friend with same space of plots gets regular payments right now. 

It looks like pool internal binding error. Everything was ok, and then broke.

![image](https://user-images.githubusercontent.com/83848743/117573793-88d9ba80-b0e2-11eb-990b-02ea6126a21d.png)
![image](https://user-images.githubusercontent.com/83848743/117573801-9b53f400-b0e2-11eb-8259-7be1b456b901.png)
![image](https://user-images.githubusercontent.com/83848743/117573833-b888c280-b0e2-11eb-92ea-a82ed3dffc63.png)
![image](https://user-images.githubusercontent.com/83848743/117574294-22a26700-b0e5-11eb-82bd-5633f365ceda.png)
![image](https://user-images.githubusercontent.com/83848743/117574331-4bc2f780-b0e5-11eb-911a-23b081d37d20.png)

**Comment by degrott** [comment]
same problem

**Comment by DanDod** [comment]
After few days, I understand how it works. Date appears in the column when worker found PROOF. And when it happens you receive payments for 24 hours.
